// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMfQvVOMHJ4PSRTvSVJXUsaOpjoJRtiFE',
    appId: '1:437637375407:web:ac390f2895bdf794cf3b5a',
    messagingSenderId: '437637375407',
    projectId: 'conversingodb',
    authDomain: 'conversingodb.firebaseapp.com',
    storageBucket: 'conversingodb.appspot.com',
    measurementId: 'G-B9JM3PBL3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIcueeCg-TaUvb8O_qmALE9v3Cjg0Uylo',
    appId: '1:437637375407:android:97ca498a71ddece7cf3b5a',
    messagingSenderId: '437637375407',
    projectId: 'conversingodb',
    storageBucket: 'conversingodb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQSEQ4oNArIL6JcVa5oNUwHzcW89AB2y0',
    appId: '1:437637375407:ios:7710718239483059cf3b5a',
    messagingSenderId: '437637375407',
    projectId: 'conversingodb',
    storageBucket: 'conversingodb.appspot.com',
    iosClientId: '437637375407-sim6ed1bg6l4sja8eir7so4tmcktmg9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLogin6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQSEQ4oNArIL6JcVa5oNUwHzcW89AB2y0',
    appId: '1:437637375407:ios:7710718239483059cf3b5a',
    messagingSenderId: '437637375407',
    projectId: 'conversingodb',
    storageBucket: 'conversingodb.appspot.com',
    iosClientId: '437637375407-sim6ed1bg6l4sja8eir7so4tmcktmg9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLogin6',
  );
}
